url: "https://www.madrascoder.com" # the base hostname & protocol for your site, e.g. http://example.com
# url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Madras Coder" # the name of your site, e.g. ACME Corp.

# Site Variables
right-arrow: '&#8594;'
left-arrow: '&#8592;'
up-arrow: '&#8593;'
down-arrow: '&#8595;'