# url: "https://www.madrascoder.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "http://localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Madras Coder" # the name of your site, e.g. ACME Corp.

